export interface Product {
  id: string;
  name: string;
  company: string;
  cat: string;
  price: number;
  img: string;
  rx: boolean;
  molecules: string;
  packing: string;
  format: 'Tablets' | 'Suspension' | 'Injection' | 'Cream' | 'Ointment' | 'Powder' | 'Shampoo' | 'Soap' | 'Syrup' | 'Sachet' | 'Liquid' | 'Capsule' | 'Other';
  description: string;
  type?: 'Popular' | 'Focus';
}

export const products: Product[] = [
  // ANTI-INFECTIVES (1-24)
  {
    id: "dr-reddy-1",
    name: "Cefiwok CV",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 320.50,
    img: "https://picsum.photos/seed/dr1/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefixime 200 mg + Clavulanic acid 125 mg",
    packing: "10x1x10's",
    description: "Cefiwok CV is a potent combination antibiotic. Cefixime belongs to the cephalosporin group and works by inhibiting bacterial cell wall synthesis. Clavulanic acid is a beta-lactamase inhibitor that prevents bacteria from destroying Cefixime, making it highly effective against resistant bacterial strains."
  },
  {
    id: "dr-reddy-2",
    name: "Cefiwok-O Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 192.50,
    img: "https://picsum.photos/seed/dr2/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefixime 200mg + Ofloxacin 200mg",
    packing: "10x10's",
    description: "A dual-action antibiotic combining Cefixime (Cephalosporin) and Ofloxacin (Fluoroquinolone). This combination provides a broad spectrum of activity against both aerobic and anaerobic bacteria, commonly used for complicated respiratory and urinary tract infections."
  },
  {
    id: "dr-reddy-3",
    name: "Fluerma 150",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 13.40,
    img: "https://picsum.photos/seed/dr3/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Fluconazole 150mg",
    packing: "50X1X1",
    description: "Fluerma 150 contains Fluconazole, a powerful antifungal medication. It works by stopping the growth of certain types of fungus and is used to treat a variety of fungal and yeast infections."
  },
  {
    id: "dr-reddy-4",
    name: "Norilet OZ Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 107.80,
    img: "https://picsum.photos/seed/dr4/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Ofloxacin 200mg + Ornidazole 500mg",
    packing: "20x10's",
    description: "A combination medicine used to treat gastrointestinal infections such as acute diarrhea or dysentery. Ofloxacin kills bacteria while Ornidazole kills amoeba and other infectious microorganisms."
  },
  {
    id: "dr-reddy-5",
    name: "ORO-CV Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 208.36,
    img: "https://picsum.photos/seed/dr5/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Amoxycillin 500mg + Clavulanic Acid 125mg",
    packing: "10x1x10's",
    description: "A gold-standard antibiotic combination. Amoxycillin is a broad-spectrum penicillin, and Clavulanic Acid protects it from being broken down by bacterial enzymes, ensuring efficacy against a wide range of common infections."
  },
  {
    id: "dr-reddy-6",
    name: "Podoxim 200 Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 208.50,
    img: "https://picsum.photos/seed/dr6/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefpodoxime Tablets 200mg",
    packing: "10x10's",
    description: "Podoxim 200 contains Cefpodoxime, a third-generation cephalosporin antibiotic. It is highly effective against a variety of bacterial infections, including those of the respiratory tract, urinary tract, and skin."
  },
  {
    id: "dr-reddy-7",
    name: "Podoxim CV DS",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 135.00,
    img: "https://picsum.photos/seed/dr7/600/600",
    rx: true,
    format: "Suspension",
    molecules: "Cefpodoxime 50mg + Clavulanic acid 31.25mg",
    packing: "8x1x30 ml",
    description: "A pediatric dry suspension combining Cefpodoxime and Clavulanic Acid. This formulation provides enhanced stability and efficacy for treating moderate to severe bacterial infections in children."
  },
  {
    id: "dr-reddy-8",
    name: "Podoxim DS 100 (Glass)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 174.75,
    img: "https://picsum.photos/seed/dr8/600/600",
    rx: true,
    format: "Suspension",
    molecules: "Cefpodoxime 100mg/5ml",
    packing: "3 X 4 X 2 X 1",
    description: "High-strength Cefpodoxime oral suspension in a premium glass bottle for better stability. Used for treating various bacterial infections in children where a 100mg/5ml concentration is required."
  },
  {
    id: "dr-reddy-10",
    name: "Podoxim-Cv 200 Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 396.00,
    img: "https://picsum.photos/seed/dr10/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefpodoxime proxetil 200mg + Clavulanic Acid 125mg",
    packing: "10X1X10's",
    description: "A powerful combination of Cefpodoxime Proxetil and Clavulanic Acid. This medication is used for treating more resistant bacterial infections of the lungs, throat, and urinary tract."
  },
  {
    id: "dr-reddy-13",
    name: "Powercef Injection",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 71.01,
    img: "https://picsum.photos/seed/dr13/600/600",
    rx: true,
    format: "Injection",
    molecules: "Ceftriaxone 1g with WFI",
    packing: "20x1x1's",
    description: "Powercef (Ceftriaxone) is a broad-spectrum injectable antibiotic used for serious infections like meningitis, sepsis, and surgical prophylaxis. Supplied with Sterile Water for Injection."
  },
  {
    id: "dr-reddy-14",
    name: "Powercef T",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 224.95,
    img: "https://picsum.photos/seed/dr14/600/600",
    rx: true,
    format: "Injection",
    molecules: "Ceftriaxone + Tazobactam",
    packing: "25 X 1",
    description: "A combination of Ceftriaxone and Tazobactam. Tazobactam is a beta-lactamase inhibitor that extends the spectrum of Ceftriaxone to include many beta-lactamase-producing bacteria."
  },
  {
    id: "dr-reddy-15",
    name: "Powercef-S Injection",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 202.50,
    img: "https://picsum.photos/seed/dr15/600/600",
    rx: true,
    format: "Injection",
    molecules: "Ceftriaxone & Sulbactam 1.5g",
    packing: "10x1x1's",
    description: "A premium injectable combination of Ceftriaxone and Sulbactam. Used for severe hospital-acquired infections and cases where resistance to single-agent antibiotics is suspected."
  },
  {
    id: "dr-reddy-16",
    name: "Tricefuro 250",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 302.15,
    img: "https://picsum.photos/seed/dr16/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefuroxime Axetil 250mg",
    packing: "10 X 1 X 10",
    description: "Tricefuro contains Cefuroxime Axetil, a second-generation cephalosporin. It is highly effective against respiratory tract infections, sinus infections, and skin infections."
  },
  {
    id: "dr-reddy-17",
    name: "Tricefuro 500",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 586.04,
    img: "https://picsum.photos/seed/dr17/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefuroxime Axetil 500mg",
    packing: "10 X 1 X 10",
    description: "Double strength Cefuroxime Axetil for more severe or chronic bacterial infections. Ensures high peak plasma concentrations for effective bacterial eradication."
  },
  {
    id: "dr-reddy-18",
    name: "Tricefuro CV",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 650.50,
    img: "https://picsum.photos/seed/dr18/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Cefuroxime Axetil + Clavulanic Acid",
    packing: "10X1X10",
    description: "Advanced combination of Cefuroxime and Clavulanic Acid. This combination overcomes bacterial resistance, providing a reliable treatment option for complex infections."
  },
  {
    id: "dr-reddy-19",
    name: "Fapenro 200",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 660.00,
    img: "https://picsum.photos/seed/dr19/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Faropenem 200mg",
    packing: "10 X 1 X 6",
    description: "Fapenro 200 contains Faropenem, a unique penem antibiotic. It has a broad spectrum of activity and is often used for severe respiratory and skin infections that do not respond to other antibiotics."
  },
  {
    id: "dr-reddy-20",
    name: "Fapenro ER 300",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 830.00,
    img: "https://picsum.photos/seed/dr20/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Faropenem 300mg Extended Release",
    packing: "10 X 1 X 6",
    description: "Extended-release Faropenem for sustained therapeutic levels and improved patient compliance. Ideal for once-daily dosing in chronic or severe bacterial infections."
  },
  {
    id: "dr-reddy-21",
    name: "Rifinimx 200",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 251.50,
    img: "https://picsum.photos/seed/dr21/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Rifaximin 200mg",
    packing: "10 X 1 X 10",
    description: "Rifinimx 200 contains Rifaximin, a non-absorbable antibiotic. It acts locally in the gastrointestinal tract and is used to treat traveler's diarrhea and irritable bowel syndrome."
  },
  {
    id: "dr-reddy-22",
    name: "Rifinimx 400",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 520.25,
    img: "https://picsum.photos/seed/dr22/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Rifaximin 400mg",
    packing: "10 X 1 X 10",
    description: "Standard dose Rifaximin for the prevention of hepatic encephalopathy recurrence and treatment of small intestinal bacterial overgrowth (SIBO)."
  },
  {
    id: "dr-reddy-23",
    name: "Rifinimx 550",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 602.25,
    img: "https://picsum.photos/seed/dr23/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Rifaximin 550mg",
    packing: "10 X 1 X 10",
    description: "High-dose Rifaximin specifically indicated for the reduction in risk of overt hepatic encephalopathy recurrence in adults."
  },
  {
    id: "dr-reddy-24",
    name: "Tri-Cefuro Inj",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 386.02,
    img: "https://picsum.photos/seed/dr24/600/600",
    rx: true,
    format: "Injection",
    molecules: "Cefuroxime 1500mg with WFI",
    packing: "8 X 1 X 1",
    description: "Injectable Cefuroxime (1.5g) for intensive care settings. Provides broad-spectrum coverage against many Gram-positive and Gram-negative organisms."
  },

  // DERMATOLOGY (25-33)
  {
    id: "dr-reddy-25",
    name: "Baxysporin Powder",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 85.00,
    img: "https://picsum.photos/seed/dr25/600/600",
    rx: false,
    format: "Powder",
    molecules: "Neomycin sulphate IP 5mg + Bacitracin zinc IP 250 units + Sulphacetamide sodium IP 60 mg",
    packing: "10x10g",
    description: "Baxysporin Powder is a triple antibiotic powder containing Neomycin, Bacitracin, and Sulphacetamide. It is used to prevent and treat minor skin infections caused by small cuts, scrapes, or burns. Neomycin and Bacitracin kill bacteria, while Sulphacetamide inhibits their growth.",
    type: "Focus"
  },
  {
    id: "dr-reddy-26",
    name: "Candigurd B",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 98.00,
    img: "https://picsum.photos/seed/dr26/600/600",
    rx: true,
    format: "Cream",
    molecules: "Clotrimazole 1% w/w + Beclometasone Dipropionate 0.025% Cream",
    packing: "20x1x10g",
    description: "Candigurd B Cream is a combination medicine used to treat various types of skin infections, typically those associated with inflammation and itching. Clotrimazole is an antifungal that stops the growth of fungi, and Beclometasone is a steroid that reduces redness, swelling, and itchiness.",
    type: "Focus"
  },
  {
    id: "dr-reddy-27",
    name: "Candigurd Powder (Small)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 104.50,
    img: "https://picsum.photos/seed/dr27/600/600",
    rx: false,
    format: "Powder",
    molecules: "Clotrimazole 1% w/w Powder",
    packing: "6x1's",
    description: "Candigurd Powder contains Clotrimazole, a broad-spectrum antifungal. It is effective for treating prickly heat, fungal infections caused by sweat and moisture, and skin irritation in folds of the body.",
    type: "Focus"
  },
  {
    id: "dr-reddy-28",
    name: "Candigurd Powder (Large)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 148.50,
    img: "https://picsum.photos/seed/dr28/600/600",
    rx: false,
    format: "Powder",
    molecules: "Clotrimazole 1% w/w Powder",
    packing: "5x1's",
    description: "Standard antifungal dusting powder for larger areas or prolonged use. Prevents fungal growth and keeps the skin dry and comfortable.",
    type: "Focus"
  },
  {
    id: "dr-reddy-29",
    name: "Eclospan Cream",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 188.50,
    img: "https://picsum.photos/seed/dr29/600/600",
    rx: true,
    format: "Cream",
    molecules: "Beclomethasone dipropionate (0.025% w/w) + Neomycin Sulphate (0.5% w/w) + Miconazole Nitrate (2% w/w)",
    packing: "25x1x15g",
    description: "A comprehensive triple-action cream. Beclomethasone reduces inflammation, Neomycin treats bacterial infections, and Miconazole treats fungal infections, making it ideal for mixed skin infections.",
    type: "Focus"
  },
  {
    id: "dr-reddy-30",
    name: "Eclospan M",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 225.00,
    img: "https://picsum.photos/seed/dr30/600/600",
    rx: true,
    format: "Cream",
    molecules: "Mometasone (0.1 % w/w) Cream",
    packing: "20x1x10g",
    description: "Eclospan M contains Mometasone, a medium-potency corticosteroid. It is used to reduce the swelling, itchiness, and redness of various skin conditions such as eczema and psoriasis.",
    type: "Focus"
  },
  {
    id: "dr-reddy-31",
    name: "Eclospan S",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 182.00,
    img: "https://picsum.photos/seed/dr31/600/600",
    rx: true,
    format: "Ointment",
    molecules: "Clobetasol 0.05% w/w + Salicylic Acid 3% w/w Ointment",
    packing: "20x1x20g",
    description: "A potent combination of Clobetasol (steroid) and Salicylic Acid (keratolytic). Used to treat chronic plaque psoriasis and other scaly skin conditions where thick skin needs to be softened for better steroid penetration.",
    type: "Focus"
  },
  {
    id: "dr-reddy-32",
    name: "Ketoluxe ZPTO",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 410.00,
    img: "https://picsum.photos/seed/dr32/600/600",
    rx: false,
    format: "Shampoo",
    molecules: "Ketoconazole 2% w/v + Pyrithione Zinc 1% w/v Shampoo",
    packing: "6 X 1 X 100ml",
    description: "Ketoluxe ZPTO is an anti-dandruff shampoo combining two active ingredients. Ketoconazole is an antifungal that kills dandruff-causing fungi, while Pyrithione Zinc helps regulate scalp health and reduces flaking.",
    type: "Focus"
  },
  {
    id: "dr-reddy-33",
    name: "Candigurd Soap",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 95.00,
    img: "https://picsum.photos/seed/dr33/600/600",
    rx: false,
    format: "Soap",
    molecules: "Sulfiram (5%) Soap",
    packing: "12 X 1 (Shrink Wrap)",
    description: "Candigurd Soap with Sulfiram is an antiseptic soap used for the treatment and prevention of scabies and other skin parasites. It helps maintain skin hygiene and prevents the spread of skin infections.",
    type: "Focus"
  },

  // GASTRO INTESTINAL (34-54)
  {
    id: "dr-reddy-34",
    name: "Omez Lax L (100ml)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 131.25,
    img: "https://picsum.photos/seed/dr34/600/600",
    rx: false,
    format: "Suspension",
    molecules: "Lactulose Solution 10g/15ml",
    packing: "100ml",
    description: "Omez Lax L contains Lactulose, a synthetic sugar used to treat constipation. It works by drawing water into the colon, which softens the stool and makes it easier to pass. It is also used in the management of hepatic encephalopathy.",
    type: "Focus"
  },
  {
    id: "dr-reddy-35",
    name: "Omez Lax L (200ml)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 262.79,
    img: "https://picsum.photos/seed/dr35/600/600",
    rx: false,
    format: "Suspension",
    molecules: "Lactulose Solution 10g/15ml",
    packing: "200ml",
    description: "Double volume Lactulose solution for extended treatment of chronic constipation or hepatic conditions. Safe for long-term use under medical supervision.",
    type: "Focus"
  },
  {
    id: "dr-reddy-36",
    name: "Omezyme (Pineapple)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 160.00,
    img: "https://picsum.photos/seed/dr36/600/600",
    rx: false,
    format: "Syrup",
    molecules: "Diastase (50mg/5ml) + Pepsin (10mg/5ml) -- Syrup (Pineapple Flavor)",
    packing: "200ml",
    description: "Omezyme is a digestive syrup containing Diastase and Pepsin. Diastase helps in the digestion of starch and carbohydrates, while Pepsin helps in the digestion of proteins, aiding in overall digestion and relieving acidity or bloating.",
    type: "Focus"
  },
  {
    id: "dr-reddy-37",
    name: "Omezyme (Saunf)",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 160.00,
    img: "https://picsum.photos/seed/dr37/600/600",
    rx: false,
    format: "Syrup",
    molecules: "Diastase (50mg/5ml) + Pepsin (10mg/5ml) -- Syrup (Saunf Flavor)",
    packing: "200ml",
    description: "Digestive enzyme supplement in a pleasant Fennel (Saunf) flavor. Helps improve digestion and reduces symptoms of dyspepsia and abdominal discomfort.",
    type: "Focus"
  },
  {
    id: "dr-reddy-38",
    name: "Rebalanz ORS",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 22.19,
    img: "https://picsum.photos/seed/dr38/600/600",
    rx: false,
    format: "Sachet",
    molecules: "Rebalanz ORS Powder 21gms",
    packing: "30x21g",
    description: "Rebalanz ORS is a WHO-recommended Oral Rehydration Salt formula used to replenish fluids and electrolytes lost due to dehydration, typically caused by diarrhea or vomiting. It contains a precise balance of salts and glucose to ensure rapid rehydration.",
    type: "Focus"
  },
  {
    id: "dr-reddy-39",
    name: "Rebalanz ORS Apple",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 29.40,
    img: "https://picsum.photos/seed/dr39/600/600",
    rx: false,
    format: "Liquid",
    molecules: "Oral Rehydration Salt - WHO recommended formula Apple flavor solution",
    packing: "30x1x200ml",
    description: "Ready-to-drink Oral Rehydration Solution in a refreshing Apple flavor. Perfect for immediate use in children and adults to manage dehydration quickly and effectively.",
    type: "Focus"
  },
  {
    id: "dr-reddy-40",
    name: "Rebalanz ORS Orange",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 29.40,
    img: "https://picsum.photos/seed/dr40/600/600",
    rx: false,
    format: "Liquid",
    molecules: "Oral Rehydration Salt - WHO recommended formula Orange flavor solution",
    packing: "30x1x200ml",
    description: "Ready-to-drink Oral Rehydration Solution in a vibrant Orange flavor. Designed for rapid fluid and electrolyte replacement according to WHO guidelines.",
    type: "Focus"
  },
  {
    id: "dr-reddy-41",
    name: "Rediout + Chew Tab",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 35.00,
    img: "https://picsum.photos/seed/dr41/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Albendazole (400mg) + Ivermectin (6mg)",
    packing: "10x10's",
    description: "Anti-parasitic combination of Albendazole and Ivermectin. Used for the treatment of various parasitic worm infestations, providing a dual-action approach for broader efficacy.",
    type: "Focus"
  },
  {
    id: "dr-reddy-42",
    name: "Rediout Chew Tab",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 9.26,
    img: "https://picsum.photos/seed/dr42/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Albendazole (400 mg)",
    packing: "10x10's",
    description: "Contains Albendazole, a broad-spectrum anthelmintic agent. Effective against roundworms, hookworms, and other common intestinal parasites in a convenient chewable format.",
    type: "Focus"
  },
  {
    id: "dr-reddy-43",
    name: "Supadrot DS",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 160.00,
    img: "https://picsum.photos/seed/dr43/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Drotaverine (80 mg)",
    packing: "20X15",
    description: "High-strength Drotaverine, an antispasmodic medication used to relieve smooth muscle spasms, especially in the gastrointestinal, biliary, and renal tracts.",
    type: "Focus"
  },
  {
    id: "dr-reddy-44",
    name: "Udiwok 300 Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 637.00,
    img: "https://picsum.photos/seed/dr44/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Ursodeoxycholic Acid 300mg",
    packing: "10x15's",
    description: "Contains Ursodeoxycholic Acid, a naturally occurring bile acid used to dissolve certain types of cholesterol gallstones and treat chronic liver diseases like primary biliary cirrhosis.",
    type: "Focus"
  },
  {
    id: "dr-reddy-45",
    name: "Udiwok 150 Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 231.50,
    img: "https://picsum.photos/seed/dr45/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Ursodeoxycholic Acid 150mg",
    packing: "10x10's",
    description: "Lower strength Ursodeoxycholic Acid for maintenance therapy or specific titration in hepatic disorders and gallstone management.",
    type: "Focus"
  },
  {
    id: "dr-reddy-46",
    name: "Zovanta CT",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 277.98,
    img: "https://picsum.photos/seed/dr46/600/600",
    rx: true,
    format: "Capsule",
    molecules: "Cinitapride (3mg) SR + Pantoprazole (40mg) EC",
    packing: "10x1x10's",
    description: "Advanced combination of Cinitapride (prokinetic) and Pantoprazole (PPI). Used for treating gastro-esophageal reflux disease (GERD) and associated dyspepsia where delayed gastric emptying is a factor.",
    type: "Focus"
  },
  {
    id: "dr-reddy-47",
    name: "Zovanta D",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 121.63,
    img: "https://picsum.photos/seed/dr47/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Pantoprazole 40mg + Domperidone 10mg",
    packing: "10X15's",
    description: "Effective combination of Pantoprazole for acid suppression and Domperidone for nausea control. Indicated for acid reflux, ulcers, and bloating.",
    type: "Focus"
  },
  {
    id: "dr-reddy-48",
    name: "Zovanta DSR Capsules",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 248.00,
    img: "https://picsum.photos/seed/dr48/600/600",
    rx: true,
    format: "Capsule",
    molecules: "Pantoprazole 40mg + Domperidone 30mg prolonged release",
    packing: "10X15's",
    description: "Prolonged-release combination for sustained relief from acid reflux and heartburn, especially when accompanied by persistent nausea or gastroparesis.",
    type: "Focus"
  },
  {
    id: "dr-reddy-49",
    name: "Zovanta Injection",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 57.48,
    img: "https://picsum.photos/seed/dr49/600/600",
    rx: true,
    format: "Injection",
    molecules: "Pantoprazole for Injection BP 40mg",
    packing: "10X1X1",
    description: "Injectable Pantoprazole for rapid and potent reduction of gastric acid production in acute clinical settings like severe peptic ulcers or surgical prophylaxis.",
    type: "Focus"
  },
  {
    id: "dr-reddy-50",
    name: "Zovanta Tablets",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 211.00,
    img: "https://picsum.photos/seed/dr50/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Pantoprazole 40mg",
    packing: "10X15's",
    description: "Pure Pantoprazole (40mg) for the reliable treatment of peptic ulcers, GERD, and hypersecretory conditions like Zollinger-Ellison syndrome.",
    type: "Focus"
  },
  {
    id: "dr-reddy-51",
    name: "Comiffin+",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 220.00,
    img: "https://picsum.photos/seed/dr51/600/600",
    rx: false,
    format: "Suspension",
    molecules: "Magnesium hydroxide (11.25ml) + Paraffin oil (3.75ml) + Sodium Picosulfate (10mg)",
    packing: "170ml",
    description: "A comprehensive triple-action laxative. Magnesium hydroxide, Paraffin oil, and Sodium Picosulfate work together to provide effective relief from constipation by softening the stool and stimulating bowel motility.",
    type: "Focus"
  },
  {
    id: "dr-reddy-52",
    name: "Supadrot",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 130.00,
    img: "https://picsum.photos/seed/dr52/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Drotaverine Tablets 40mg",
    packing: "20 X 15",
    description: "Standard strength Drotaverine for relieving pain associated with smooth muscle spasms in abdominal cramps, menstrual pain, and irritable bowel syndrome.",
    type: "Focus"
  },
  {
    id: "dr-reddy-53",
    name: "Supadrot M",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 200.00,
    img: "https://picsum.photos/seed/dr53/600/600",
    rx: true,
    format: "Tablets",
    molecules: "Drotaverine (80mg) + Mefenamic Acid (250mg)",
    packing: "20 X 10",
    description: "Dual-action relief combining Drotaverine (antispasmodic) and Mefenamic Acid (analgesic). Specifically indicated for severe spasmodic pain in conditions like dysmenorrhea or colic.",
    type: "Focus"
  },
  {
    id: "dr-reddy-54",
    name: "Zovanta L",
    company: "Dr. Reddy's",
    cat: "Pharmaceuticals",
    price: 200.35,
    img: "https://picsum.photos/seed/dr54/600/600",
    rx: true,
    format: "Capsule",
    molecules: "Pantoprazole 40mg + Levosulpiride 75mg",
    packing: "10x1x10's",
    description: "Combines a potent PPI (Pantoprazole) with a prokinetic (Levosulpiride). Ideal for GERD complicated by functional dyspepsia or diabetic gastroparesis.",
    type: "Focus"
  }
];